### ISSUE TITLE
Make list of Objects understandable to AsyncAPI

### ISSUE THREAD

**Issue by leodennis** [springwolf/springwolf-core#119]
Hi,

I'm having trouble generating code with AsyncAPI from asyncapi jsons generated with springwolf.

As example I have a simple class which is expected in one of my kafka consumers:

```
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class NotificationDto {
    private String topic;
    private List<NotificationData> data;
}
```

This will result in:

```
"NotificationDto": {
  "type": "object",
  "properties": {
    "topic": {
      "type": "string",
      "exampleSetFlag": false,
      "types": [
        "string"
      ]
    },
    "data": {
      "type": "array",
      "exampleSetFlag": false,
      "items": {
        "$ref": "#/components/schemas/NotificationData",
        "exampleSetFlag": false
      },
      "types": [
        "array"
      ]
    }
  "example": {
    "topic": "string",
    "data": [
      {
        "key": "string",
        "value": "string"
      }
    ]
  },
  "exampleSetFlag": true
}
```

Now when I generate code with asyncapi and java-spring-template I get
```
public class NotificationDto {
    
    private @Valid String topic;
    
    private @Valid List<AnonymousSchema3> dataList;
   
    // ... methods
}
```

I also get the infromation that AnonymousSchema were generated and 

> to move such elements to child of "schemas:" to define proper names. If changing of data model is not possible, you may use "$id" to set name

Now here comes my question: How can I change my Class and use springwolf to produce an understandable json for asyncapi so that it does not generated AnonymousSchemas (but rather the correct Class I used).
The problem seems to be with any kind of collections that do not contain primitive types.

Once example would be to add $id, then it is generated correctly but I don't know how I would do that in the java code as I obviously don't want to edit the generated json by hand. Is this somehow possible with  `@Schema` from swagger annotations?
```
"data": {
  "type": "array",
  "exampleSetFlag": false,
  "items": {
    "$id": "NotificationData",
    "$ref": "#/components/schemas/NotificationData",
    "exampleSetFlag": false
  },
  "types": [
    "array"
  ]
}
```

Any help would be apreciated.

**Comment by stavshamir** [comment]
Hi, @leodennis , thanks for reporting this! Does your last example (with the `$id` field) work? If yes, I can try to set the `$id` field of the schema for complex objects.

Could you please provide the entire message containing this sentence?
> to move such elements to child of "schemas:" to define proper names. If changing of data model is not possible, you may use "$id" to set name

**Comment by leodennis** [comment]
Hi stavshamir 🙂
yes ifI manually add the `$id` it works

Here is the full message:
```
Following AnonymousSchema classes were generated in DTO classes:
com/test/notification/model/AnonymousSchema3.java

This may be a result of explicit (composition, inheritance, array items) Schema Object definition e.g.

    schemas:
      NamedObject:
      type: object
        properties:
          field:
            type: array
            items:
              type: object #Anonymous object
              properties:
                field:
                  type: string

OR

    messages:
      Message:
        payload:
          type: object #Anonymous object
          properties:

Please move such elements to child of "schemas:" to define proper names.
If changing of data model is not possible, you may use "$id" to set name e.g.

    properties:
      field:
        type: array
        items:
          $id: ArrayElement #Name of object
          type: object
          properties:
            field:
              type: string

```
