### ISSUE TITLE
Add support for Payload Kafka Key Types

### ISSUE THREAD

**Issue by Sonic-Rage** [springwolf/springwolf-core#563]
We utilize an Object as a Key to send events with Kafka.   It would be great if the scanner could recognize objects used for Kafka Keys to add the schemas automatically to message binding. 

Here is a sample of a listener that we use with Spring Kafka

 @KafkaHandler
 public void consumeMessage(
            @Headers MessageHeaders headers,
            @Header(KafkaHeaders.RECEIVED_KEY) KeyObject key,
            @Payload(required = false) PayloadObject payload) {

**Comment by ctasada** [comment]
Hi @Sonic-Rage I was looking into this ticket. Would be fair to assume that, given something like

```java
    @KafkaHandler
    public void receiveExamplePayload(
            @Headers MessageHeaders headers,
            @Header(KafkaHeaders.RECEIVED_KEY) String key,
            @Payload(required = false) ExamplePayloadDto payload) {
        log.info("Received new message in {}: {}", TOPIC, payload.toString());
    }
```

Should generate 
```yaml
        "message": {
          "schemaFormat": "application/vnd.oai.openapi+json;version=3.0.0",
          "name": "io.github.stavshamir.springwolf.example.kafka.dtos.AnotherPayloadDto",
          "title": "AnotherPayloadDto",
          "payload": {
            "$ref": "#/components/schemas/io.github.stavshamir.springwolf.example.kafka.dtos.AnotherPayloadDto"
          },
          "headers": {
            "type": "object",
            "properties": {
                "id": {
                   "type": "string"
                 },
                "kafka_receivedMessageKey": {
                   "type": "string"
                 },
                "timestamp": {
                   "type": "string"
                 },
          },
          "bindings": {
            "kafka": {
              "bindingVersion": "0.4.0"
            }
          }
        }
```
We are heavily working on the next release, but we can check how to improve this case. Can you confirm that would be your expectation?
