### ISSUE TITLE
Add support for Kotlin Serialization

### ISSUE THREAD

**Issue by ctasada** [springwolf/springwolf-core#589]
Springwolf doesn't support the generation of AsyncAPI components when used with Kotlin

Example:
```
@Serializable
data class Period(
    @SerialName("start_date")
    val startDate: String,
    @SerialName("period_end")
    val endDate: String,
)
```

The outcome looks like:
```
    Period:
      required:
        - endDate
        - startDate
      type: object
      properties:
        endDate:
          type: string
        startDate:
          type: string
```

Ignoring the `@SerialName` annotation.
