### ISSUE TITLE
`use-fqn` overrides SpringDoc configuration

### ISSUE THREAD

**Issue by ctasada** [springwolf/springwolf-core#635]
**Describe the bug**
In an application that uses both `SpringDoc` for OpenApi and `Spring-Wolf` for AsyncAPI, the usage of `spring-wolf.use-fqn` overrides the one used by `springdoc.use-fqn`

I just realized after upgrading an application to spring-wolf:core 1.0.0 since the `use-fqn` is now defaulting to `true` the issue may be older.

**Code example**
Having a SpringBoot application with both dependencies, and the application.yml configured like
```
springdoc:
    use-fqn: true
    api-docs:
        enabled: true
        
springwolf:
    enabled: true
    use-fqn: false
```

I would expect the `springdoc` generated OpenAPI uses the FQN, but it's not the case. The value used for `spring-wolf.use-fqn` is alway taking precedence.

**Stack trace and error logs**
None
