### ISSUE TITLE
Schemas converted to String type, when default content type changed to application/yaml 

### ISSUE THREAD

**Issue by MrOli1412** [springwolf/springwolf-core#756]
**Describe the bug**
When I changed `default-content-type` to `application/yaml`
generated file and springwolf-ui received in Schemas section all POJO's as String object. 

**Dependencies and versions used**
tested on latest master version(1.3.0-SNAPSHOT) and 1.2.0  of
springwolf-amqp
springwolf-ui

**Code example**
Proper working 
**springwolf.docket.default-content-type=application/json** (default)
![proper_working](https://github.com/springwolf/springwolf-core/assets/46925506/8a50e552-bc11-448e-b78e-72858e1642cb)

Issue
**springwolf.docket.default-content-type=application/yaml**
I was working on yours  AMQP example (https://github.com/springwolf/springwolf-core/tree/master/springwolf-examples/springwolf-amqp-example), and I changed  **default-content-type** in **docker-compose.yaml** 

```
version: '3'
services:
  app:
    image: stavshamir/springwolf-amqp-example:${SPRINGWOLF_VERSION}
    environment:
      - SPRINGWOLF_DOCKET_DEFAULT-CONTENT-TYPE=application/yaml
    links:
      - amqp
    ports:
      - "8080:8080"
    depends_on:
      - amqp

  amqp:
    image: rabbitmq:3.8-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

```
Result: 
![issue](https://github.com/springwolf/springwolf-core/assets/46925506/d894d777-2542-404e-b636-e6e604842465)
