### ISSUE TITLE
@AsyncOperation.Headers.Header#value is mandatory and renders as "enum"

### ISSUE THREAD

**Issue by ccudennec-otto** [springwolf/springwolf-core#791]
**Describe the bug**
When I want to document the headers of my operation, I need to specify the "value" of the header, e.g.:
```
@AsyncOperation.Headers.Header(name = "ce_id", value="foo" description = "CloudEvent Id")
```

This will render as the following YAML:
```
        ce_id:
          type: string
          description: CloudEvent Id
          enum:
            - foo
          examples:
            - foo
```

By defining the list of possible values using "enum" it should not be possible to send different values than the one defined.
IMHO it should be possible to not define `Header#value` if the value is dynamic.
Did I misread the specification?

**Dependencies and versions used**
`springwolf-core` version `1.2.0`.

Thanks!

Christopher
