### ISSUE TITLE
Support for a polymorphic payload

### ISSUE THREAD

**Issue by dabeck81** [springwolf/springwolf-core#891]
**Describe the feature request**
When using a listener with an abstract class (VehicleBase), I want to be able to set all polymorphic classes implementing the abstract class as a payload with "oneOf"(as being done with OpenApi), like so:
```
components:
  messages:
    io.github.springwolf.examples.kafka.dtos.discriminator.VehicleBase:
      headers:
        $ref: "#/components/schemas/SpringKafkaDefaultHeaders-VehicleBase"
      payload:
        schemaFormat: application/vnd.aai.asyncapi+json;version=3.0.0
        schema:
          oneOf:
            - $ref: "#/components/schemas/io.github.springwolf.examples.kafka.dtos.discriminator.VehicleElectricPayloadDto"
            - $ref: "#/components/schemas/io.github.springwolf.examples.kafka.dtos.discriminator.VehicleGasolinePayloadDto"
      name: io.github.springwolf.examples.kafka.dtos.discriminator.VehicleBase
      title: VehicleBase
      bindings:
        kafka:
          bindingVersion: 0.5.0
```

**Motivation**
My motivation for this feature request is that we currently have one queue on which all kinds of messages are transmitted. They all have a common header-part describing the data-part. So in my case the Header is the abstract-class that I would define as my payload and all implementing classes would be acceptable on that listener.

Currently, when setting an abstract class as payload a reference to the abstract class is created and the indication that the child-classes are also acceptable is lost. The reason this happens is that the payload always is set as a reference, like you can see here:
https://github.com/springwolf/springwolf-core/blob/013a9e146bdb35900e1acc8abed0e85802fd3144/springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/scanners/common/AsyncAnnotationScanner.java#L103

If the code would be adapted to set either a reference to a schema-component or either a schema itself, this would resolve a lot of issues, like:

1. Having the need of setting primitive-types as schema-components, like it is done in the code here:
https://github.com/springwolf/springwolf-core/blob/013a9e146bdb35900e1acc8abed0e85802fd3144/springwolf-core/src/main/java/io/github/springwolf/core/asyncapi/schemas/SwaggerSchemaService.java#L101
You could define the schema directly as payload, like so:
```
components:
  messages:
    PrimitiveString:
      headers:
        "$ref": "#/components/schemas/SpringRabbitListenerDefaultHeaders"
      payload:
        schemaFormat: application/vnd.aai.asyncapi+json;version=3.0.0
        schema:
          type: string                   --> schema directly instead of reference
      name: PrimitiveString
      title: PrimitiveString
      bindings:
        amqp:
          bindingVersion: 0.3.0
```
2. It would not be needed anymore to have an envelopping class, like you propose on the website: https://www.springwolf.dev/docs/configuration/documenting-messages#primitive-final-and-external-classes
3. It would resolve an actual bug in the code where the information that the payload is a List is lost. Like can be found in the Kafka-example:
https://github.com/springwolf/springwolf-core/blob/013a9e146bdb35900e1acc8abed0e85802fd3144/springwolf-examples/springwolf-kafka-example/src/main/java/io/github/springwolf/examples/kafka/consumers/ExampleConsumer.java#L39
Is translated to just the object, without the list:
https://github.com/springwolf/springwolf-core/blob/013a9e146bdb35900e1acc8abed0e85802fd3144/springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.yaml#L1106
Ideally this should be mentionned as
```
payload:
  schemaFormat: application/vnd.aai.asyncapi+json;version=3.0.0
  schema:
    type: array   --> the information that payload is a list
    items:
      "$ref": "#/components/schemas/io.github.springwolf.examples.amqp.dtos.AnotherPayloadDto"

```
4. It would open up a lot of more customizability, like polymorphism, which is my actual question :-)

**Technical details**
I played a bit around and have a working POC for polymorphism on payload. You can find it here https://github.com/springwolf/springwolf-core/pull/890. The Vehicle-example in Kafka is now working with a oneOf.
I am willing to continue the work, but first I had a couple of questions on the correct way to implement:
- As you can see the heavy lifting is happening in the PayloadService, where I added some code to determine if I need to foresee "oneOf" occurences. The code is adopted from springdoc.
- The NamedSchemaObject would ideally be called PayloadSchemaObject with either a referenceObject or schemaObject in it
- It would be nice if the payload-schema could pass through the SwaggerSchemaService, so that Schema's could be adapted with modelConverters. So that in my case the polymorphism conversion happens through a modelconverter instead of in the payloadService. The same way is happening within the spingdoc project for Openapi.
- Also to be able to support primitives, I need a bit of a pointer on exactly how you would be doing this

Let me know on any of your ideas that come to mind for going further with this
